services:
  mysql:
    image: mysql:8.0
    container_name: auction-house-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auctiondb
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3306:3306"
    volumes:
      - auction-house-data:/var/lib/mysql
    networks:
      - springboot-network

volumes:
  auction-house-data:

networks:
  springboot-network: